## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes: 
  cell_layout: null
  num_cell_groups: 2
  num_init_nodes: 2
  num_layers: 20
  num_node_inputs: 2
  num_steps: 4
  reduce_cell_groups:
  - 1
  shared_primitives:
  - none
  - max_pool_3x3
  - avg_pool_3x3
  - skip_connect
  - xnor_conv_3x3
  - xnor_conv_5x5
  - xnor_dil_conv_3x3
  - xnor_dil_conv_5x5
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: 16
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: bnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  genotypes:
      CNNGenotype(normal_0=[('xnor_dil_conv_5x5', 1, 2), ('skip_connect', 0, 2), ('none',
      2, 3), ('xnor_dil_conv_5x5', 1, 3), ('none', 2, 4), ('max_pool_3x3', 1, 4), ('none',
      1, 5), ('none', 2, 5)], reduce_1=[('avg_pool_3x3', 0, 2), ('none', 1, 2), ('none',
      0, 3), ('none', 1, 3), ('none', 1, 4), ('none', 2, 4), ('none', 2, 5), ('none',
      3, 5)], normal_0_concat=[2, 3, 4, 5], reduce_1_concat=[2, 3, 4, 5])
  auxiliary_cfg: null
  auxiliary_head: True
  dropout_path_rate: 0.2
  dropout_rate: 0.1
  init_channels: 36
  num_classes: 10
  schedule_cfg:
    dropout_path_rate:
      type: add
      start: 0
      every: 1
      step: 0.000333 # 0.2/600
  stem_multiplier: 3
  inter_cell_shortcut: True
  # inter_cell_reduction_op_type: avg_pool_2x2
  inter_cell_reduction_op_type: xnor_conv_3x3_noskip
  cell_preprocess_stride: xnor_conv_bn_3x3
  cell_preprocess_normal: xnor_conv_bn_3x3
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  auxiliary_head: true
  auxiliary_weight: 0.4
  batch_size: 128
  epochs: 200
  grad_clip: 5.0
  learning_rate: 0.0005
  momentum: 0.9
  no_bias_decay: false
  optimizer_type: Adam
  optimizer_scheduler:
    eta_min: 1.e-5
    T_max: 200
    type: CosineAnnealingLR
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 3.e-6
  save_as_state_dict: true
  # multiprocess: True
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----

objective_type: classification
objective_cfg:
  {}
