## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes: 
  cell_layout: null
  num_cell_groups: 2
  num_init_nodes: 2
  num_layers: 20
  num_node_inputs: 2
  num_steps: 4
  reduce_cell_groups:
  - 1
  shared_primitives:
  - none
  - max_pool_3x3
  - avg_pool_3x3
  - skip_connect
  - xnor_conv_3x3
  - xnor_conv_5x5
  - xnor_dil_conv_3x3
  - xnor_dil_conv_5x5
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: 16
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: cnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  genotypes:
      CNNGenotype(normal_0=[('max_pool_3x3', 1, 2), ('xnor_dil_conv_5x5', 0, 2), ('skip_connect',
      1, 3), ('xnor_dil_conv_5x5', 2, 3), ('max_pool_3x3', 1, 4), ('max_pool_3x3', 0,
      4), ('max_pool_3x3', 2, 5), ('max_pool_3x3', 0, 5)], reduce_1=[('xnor_dil_conv_5x5',
      0, 2), ('xnor_dil_conv_3x3', 1, 2), ('xnor_dil_conv_5x5', 2, 3), ('max_pool_3x3',
      0, 3), ('max_pool_3x3', 1, 4), ('max_pool_3x3', 0, 4), ('xnor_dil_conv_5x5', 2,
      5), ('xnor_dil_conv_5x5', 4, 5)], normal_0_concat=[2, 3, 4, 5], reduce_1_concat=[2,
      3, 4, 5])
  auxiliary_cfg: null
  auxiliary_head: False
  dropout_path_rate: 0.2
  dropout_rate: 0.1
  init_channels: 36
  num_classes: 10
  schedule_cfg:
    dropout_path_rate:
      type: add
      start: 0
      every: 1
      step: 0.000333 # 0.2/600
  stem_multiplier: 3
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  auxiliary_head: false
  auxiliary_weight: 0.0
  batch_size: 128
  epochs: 600
  grad_clip: 5.0
  learning_rate: 0.05
  momentum: 0.9
  no_bias_decay: false
  optimizer_scheduler:
    eta_min: 0.0005
    T_max: 600
    type: CosineAnnealingLR
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 3.e-6
  save_as_state_dict: true
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----

objective_type: classification
objective_cfg:
  {}
